In [78]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.feature_selection import SelectKBest, f_regression
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)
from sklearn.tree import DecisionTreeRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.preprocessing import StandardScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Input
import tensorflow as tf

In [2]:
df = pd.read_csv("emergency_service.csv") # Data Loading
df.head()

,Timestamp,Incident_Severity,Incident_Type,Region_Type,Traffic_Congestion,Weather_Condition,Ambulance_Availability,Hospital_Capacity,Distance_to_Incident,Number_of_Injuries,Specialist_Availability,Road_Type,Emergency_Level,Ambulance_Speed,Fuel_Level,Weather_Impact,Dispatch_Coordinator,Response_Time
0,01/01/2018 00:00,Low,Cardiac Arrest,Suburban,High,Clear,Available,91,8.89,1,Unavailable,Highway,Major,43.549849,90.030756,Severe,AI,20.870220
1,01/01/2018 00:10,Low,Other,Urban,Moderate,Clear,Available,28,28.10,2,Unavailable,Highway,Critical,30.687975,88.255008,Moderate,Human,24.486195
2,01/01/2018 00:20,Medium,Cardiac Arrest,Suburban,High,Rainy,Available,83,40.43,1,Unavailable,Unpaved Road,Minor,44.456331,97.719622,No Impact,Human,18.760740
3,01/01/2018 00:30,Low,Accident,Urban,Moderate,Clear,Available,31,18.97,3,Available,Highway,Minor,35.879968,60.234672,No Impact,Human,18.169534
4,01/01/2018 00:40,Low,Cardiac Arrest,Urban,Moderate,Stormy,Available,52,16.31,3,Available,Highway,Minor,26.369383,71.083564,Moderate,Human,5.000000

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 368065 entries, 0 to 368064
Data columns (total 18 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   Timestamp                368065 non-null  object
 1   Incident_Severity        368065 non-null  object
 2   Incident_Type            368065 non-null  object
 3   Region_Type              368065 non-null  object
 4   Traffic_Congestion       368065 non-null  object
 5   Weather_Condition        368065 non-null  object
 6   Ambulance_Availability   368065 non-null  object
 7   Hospital_Capacity        368065 non-null  int64
 8   Distance_to_Incident     368065 non-null  float64
 9   Number_of_Injuries       368065 non-null  int64
 10  Specialist_Availability  368065 non-null  object
 11  Road_Type                368065 non-null  object
 12  Emergency_Level          368065 non-null  object
 13  Ambulance_Speed          368065 non-null  float64
 14  Fuel_Level               368065 non-null  float64
 15  Weather_Impact           368065 non-null  object
 16  Dispatch_Coordinator     368065 non-null  object
 17  Response_Time            368065 non-null  float64
dtypes: float64(4), int64(2), object(12)
memory usage: 50.5+ MB

In [13]:
# Data Preprocessing
df_encoded = df.copy()
df_encoded.columns

Index(['Timestamp', 'Incident_Severity', 'Incident_Type', 'Region_Type',
       'Traffic_Congestion', 'Weather_Condition', 'Ambulance_Availability',
       'Hospital_Capacity', 'Distance_to_Incident', 'Number_of_Injuries',
       'Specialist_Availability', 'Road_Type', 'Emergency_Level',
       'Ambulance_Speed', 'Fuel_Level', 'Weather_Impact',
       'Dispatch_Coordinator', 'Response_Time'],
      dtype='object')

In [8]:
df_encoded.drop("Timestamp", axis=1, inplace=True)

In [9]:
df_encoded = pd.get_dummies(df_encoded, drop_first=True)

In [10]:
X = df_encoded.drop("Response_Time", axis=1)
y = df_encoded["Response_Time"]

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42) # Train-Test Split

In [17]:
# check that everything is ok
print(X.shape)
print(y.shape)

(368065, 25)
(368065,)

In [16]:
X.head()

,Hospital_Capacity,Distance_to_Incident,Number_of_Injuries,Ambulance_Speed,Fuel_Level,Incident_Severity_Low,Incident_Severity_Medium,Incident_Type_Cardiac Arrest,Incident_Type_Fire,Incident_Type_Other,...,Weather_Condition_Stormy,Ambulance_Availability_Unavailable,Specialist_Availability_Unavailable,Road_Type_Local Road,Road_Type_Unpaved Road,Emergency_Level_Major,Emergency_Level_Minor,Weather_Impact_No Impact,Weather_Impact_Severe,Dispatch_Coordinator_Human
0,91,8.89,1,43.549849,90.030756,True,False,True,False,False,...,False,False,True,False,False,True,False,False,True,False
1,28,28.10,2,30.687975,88.255008,True,False,False,False,True,...,False,False,True,False,False,False,False,False,False,True
2,83,40.43,1,44.456331,97.719622,False,True,True,False,False,...,False,False,True,False,True,False,True,True,False,True
3,31,18.97,3,35.879968,60.234672,True,False,False,False,False,...,False,False,False,False,False,False,True,True,False,True
4,52,16.31,3,26.369383,71.083564,True,False,True,False,False,...,True,False,False,False,False,False,True,False,False,True

In [37]:
selector = SelectKBest(score_func=f_regression, k=5)
selector.fit(X, y)

SelectKBest(k=5, score_func=<function f_regression at 0x000001651D1A3EC0>)

In [38]:
feature_scores = pd.DataFrame({
    "Feature": X.columns,
    "Score": selector.scores_
})

feature_scores = feature_scores.sort_values(
    by="Score",
    ascending=False
)

feature_scores

                                Feature     Score
17  Specialist_Availability_Unavailable  2.830874
15             Weather_Condition_Stormy  2.829592
14              Weather_Condition_Rainy  2.742275
19               Road_Type_Unpaved Road  2.515680
24           Dispatch_Coordinator_Human  2.059793
9                   Incident_Type_Other  1.916161
7          Incident_Type_Cardiac Arrest  1.624567
20                Emergency_Level_Major  1.416418
4                            Fuel_Level  1.110064
22             Weather_Impact_No Impact  1.020074
11                    Region_Type_Urban  0.914066
5                 Incident_Severity_Low  0.496613
1                  Distance_to_Incident  0.495016
6              Incident_Severity_Medium  0.433103
23                Weather_Impact_Severe  0.298982
16   Ambulance_Availability_Unavailable  0.245687
3                       Ambulance_Speed  0.171136
2                    Number_of_Injuries  0.169439
21                Emergency_Level_Minor  0.075563
18                 Road_Type_Local Road  0.020564
13          Traffic_Congestion_Moderate  0.020473
12               Traffic_Congestion_Low  0.017978
8                    Incident_Type_Fire  0.012512
10                 Region_Type_Suburban  0.008833
0                     Hospital_Capacity  0.000608

In [40]:
selected_features_kbest = X.columns[selector.get_support()]
print(selected_features_kbest)

Index(['Weather_Condition_Rainy', 'Weather_Condition_Stormy',
       'Specialist_Availability_Unavailable', 'Road_Type_Unpaved Road',
       'Dispatch_Coordinator_Human'],
      dtype='object')

In [22]:
rf = RandomForestRegressor(
    n_estimators=100,
    random_state=42
)

rf.fit(X_train, y_train)

importance_df = pd.DataFrame({
    "Feature": X.columns,
    "Importance": rf.feature_importances_
})

importance_df = importance_df.sort_values(
    by="Importance",
    ascending=False
)

print(importance_df)

                                Feature  Importance
3                       Ambulance_Speed    0.195385
4                            Fuel_Level    0.191985
1                  Distance_to_Incident    0.188385
0                     Hospital_Capacity    0.137868
2                    Number_of_Injuries    0.029897
18                 Road_Type_Local Road    0.017208
22             Weather_Impact_No Impact    0.016491
17  Specialist_Availability_Unavailable    0.016060
24           Dispatch_Coordinator_Human    0.015376
9                   Incident_Type_Other    0.014363
5                 Incident_Severity_Low    0.014283
7          Incident_Type_Cardiac Arrest    0.014192
12               Traffic_Congestion_Low    0.014099
13          Traffic_Congestion_Moderate    0.013756
21                Emergency_Level_Minor    0.013329
6              Incident_Severity_Medium    0.013220
14              Weather_Condition_Rainy    0.012909
11                    Region_Type_Urban    0.012771
16   Ambulance_Availability_Unavailable    0.011762
8                    Incident_Type_Fire    0.011182
10                 Region_Type_Suburban    0.010937
19               Road_Type_Unpaved Road    0.009925
20                Emergency_Level_Major    0.009509
15             Weather_Condition_Stormy    0.008243
23                Weather_Impact_Severe    0.006864

In [24]:
selected_features = [
    "Ambulance_Speed",
    "Fuel_Level",
    "Distance_to_Incident",
    "Hospital_Capacity",
    "Number_of_Injuries"
]

X_selected = X[selected_features]

In [41]:
X_kbest = X[selected_features_kbest]

In [42]:
X_train_k, X_test_k, y_train_k, y_test_k = train_test_split(X_kbest, y, test_size=0.2, random_state=42)

In [45]:
lr_kbest = LinearRegression()
lr_kbest.fit(X_train_k, y_train_k)

LinearRegression()

In [46]:
y_pred_kbest = lr_kbest.predict(X_test_k)

In [47]:
mae_kbest = mean_absolute_error(y_test_k, y_pred_kbest)

mse_kbest = mean_squared_error(y_test_k, y_pred_kbest)

rmse_kbest = mse_kbest ** 0.5

r2_kbest = r2_score(y_test_k, y_pred_kbest)

In [48]:
print("Linear Regression + SelectKBest")

print("MAE :", mae_kbest)
print("MSE :", mse_kbest)
print("RMSE:", rmse_kbest)
print("R²  :", r2_kbest)

Linear Regression + SelectKBest
MAE : 3.9446154049685345
MSE : 23.945892706541706
RMSE: 4.893454067071817
R²  : -6.868381949010072e-05

In [25]:
X_train, X_test, y_train, y_test = train_test_split(X_selected, y, test_size=0.2, random_state=42)

In [58]:
lr = LinearRegression()
lr.fit(X_train, y_train)

LinearRegression()

In [59]:
y_pred_lr = lr.predict(X_test)

In [60]:
mae_lr = mean_absolute_error(y_test, y_pred_lr)
mse_lr = mean_squared_error(y_test, y_pred_lr)
rmse_lr = mse_lr ** 0.5
r2_lr = r2_score(y_test, y_pred_lr)

In [61]:
print("Linear Regression Results")
print("MAE :", mae_lr)
print("MSE :", mse_lr)
print("RMSE:", rmse_lr)
print("R²  :", r2_lr)

Linear Regression Results
MAE : 3.9445931579514824
MSE : 23.94666236320285
RMSE: 4.893532707891391
R²  : -0.00010082751668027967

In [62]:
dt = DecisionTreeRegressor(
    random_state=42
)

In [63]:
dt.fit(X_train_k, y_train_k)

DecisionTreeRegressor(random_state=42)

In [64]:
y_pred_dt = dt.predict(X_test_k)

In [65]:
mae_dt = mean_absolute_error(y_test_k, y_pred_dt)
mse_dt = mean_squared_error(y_test_k, y_pred_dt)
rmse_dt = mse_dt ** 0.5
r2_dt = r2_score(y_test_k, y_pred_dt)

In [66]:
print("Decision Tree Results")
print("MAE :", mae_dt)
print("MSE :", mse_dt)
print("RMSE:", rmse_dt)
print("R²  :", r2_dt)

Decision Tree Results
MAE : 3.944861462466285
MSE : 23.948409443462303
RMSE: 4.89371121373772
R²  : -0.00017379202366307744

In [69]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train_k)
X_test_scaled = scaler.transform(X_test_k)

In [70]:
knn = KNeighborsRegressor(
    n_neighbors=5
)
knn.fit(X_train_scaled, y_train_k)

KNeighborsRegressor()

In [71]:
y_pred_knn = knn.predict(X_test_scaled)

In [72]:
mae_knn = mean_absolute_error(y_test_k, y_pred_knn)

mse_knn = mean_squared_error(y_test_k, y_pred_knn)

rmse_knn = mse_knn ** 0.5

r2_knn = r2_score(y_test_k, y_pred_knn)

In [73]:
print("KNN Results")
print("MAE :", mae_knn)
print("MSE :", mse_knn)
print("RMSE:", rmse_knn)
print("R²  :", r2_knn)

KNN Results
MAE : 4.166898975696632
MSE : 26.794307153165555
RMSE: 5.17632177836401
R²  : -0.11902896320925493

In [79]:
tf.random.set_seed(42)
model = Sequential([
    Input(shape=(5,)),
    Dense(10, activation='relu'),
    Dense(1)
])

model.compile(
    optimizer='adam',
    loss='mse'
)

In [80]:
history = model.fit(
    X_train_scaled,
    y_train_k,
    epochs=50,
    batch_size=32,
    validation_split=0.2,
    verbose=1
)

Epoch 1/50
7362/7362 ━━━━━━━━━━━━━━━━━━━━ 23s 3ms/step - loss: 38.5226 - val_loss: 24.0825
Epoch 2/50
7362/7362 ━━━━━━━━━━━━━━━━━━━━ 22s 3ms/step - loss: 23.9362 - val_loss: 24.0571
Epoch 3/50
7362/7362 ━━━━━━━━━━━━━━━━━━━━ 25s 3ms/step - loss: 23.9214 - val_loss: 24.0522
Epoch 4/50
7362/7362 ━━━━━━━━━━━━━━━━━━━━ 40s 3ms/step - loss: 23.9168 - val_loss: 24.0482
Epoch 5/50
7362/7362 ━━━━━━━━━━━━━━━━━━━━ 38s 3ms/step - loss: 23.9136 - val_loss: 24.0462
Epoch 6/50
7362/7362 ━━━━━━━━━━━━━━━━━━━━ 18s 2ms/step - loss: 23.9113 - val_loss: 24.0444
Epoch 7/50
7362/7362 ━━━━━━━━━━━━━━━━━━━━ 20s 3ms/step - loss: 23.9101 - val_loss: 24.0433
Epoch 8/50
7362/7362 ━━━━━━━━━━━━━━━━━━━━ 20s 3ms/step - loss: 23.9090 - val_loss: 24.0431
Epoch 9/50
7362/7362 ━━━━━━━━━━━━━━━━━━━━ 22s 3ms/step - loss: 23.9082 - val_loss: 24.0420
Epoch 10/50
7362/7362 ━━━━━━━━━━━━━━━━━━━━ 21s 3ms/step - loss: 23.9075 - val_loss: 24.0413
Epoch 11/50
7362/7362 ━━━━━━━━━━━━━━━━━━━━ 22s 3ms/step - loss: 23.9070 - val_loss: 24.0406
Epoch 12/50
7362/7362 ━━━━━━━━━━━━━━━━━━━━ 28s 4ms/step - loss: 23.9062 - val_loss: 24.0399
Epoch 13/50
7362/7362 ━━━━━━━━━━━━━━━━━━━━ 22s 3ms/step - loss: 23.9055 - val_loss: 24.0395
Epoch 14/50
7362/7362 ━━━━━━━━━━━━━━━━━━━━ 23s 3ms/step - loss: 23.9051 - val_loss: 24.0403
Epoch 15/50
7362/7362 ━━━━━━━━━━━━━━━━━━━━ 48s 4ms/step - loss: 23.9046 - val_loss: 24.0389
Epoch 16/50
7362/7362 ━━━━━━━━━━━━━━━━━━━━ 23s 3ms/step - loss: 23.9045 - val_loss: 24.0392
Epoch 17/50
7362/7362 ━━━━━━━━━━━━━━━━━━━━ 21s 3ms/step - loss: 23.9041 - val_loss: 24.0383
Epoch 18/50
7362/7362 ━━━━━━━━━━━━━━━━━━━━ 21s 3ms/step - loss: 23.9040 - val_loss: 24.0393
Epoch 19/50
7362/7362 ━━━━━━━━━━━━━━━━━━━━ 21s 3ms/step - loss: 23.9037 - val_loss: 24.0388
Epoch 20/50
7362/7362 ━━━━━━━━━━━━━━━━━━━━ 21s 3ms/step - loss: 23.9035 - val_loss: 24.0378
Epoch 21/50
7362/7362 ━━━━━━━━━━━━━━━━━━━━ 21s 3ms/step - loss: 23.9033 - val_loss: 24.0375
Epoch 22/50
7362/7362 ━━━━━━━━━━━━━━━━━━━━ 21s 3ms/step - loss: 23.9032 - val_loss: 24.0375
Epoch 23/50
7362/7362 ━━━━━━━━━━━━━━━━━━━━ 23s 3ms/step - loss: 23.9030 - val_loss: 24.0373
Epoch 24/50
7362/7362 ━━━━━━━━━━━━━━━━━━━━ 42s 3ms/step - loss: 23.9030 - val_loss: 24.0372
Epoch 25/50
7362/7362 ━━━━━━━━━━━━━━━━━━━━ 28s 4ms/step - loss: 23.9030 - val_loss: 24.0374
Epoch 26/50
7362/7362 ━━━━━━━━━━━━━━━━━━━━ 23s 3ms/step - loss: 23.9030 - val_loss: 24.0374
Epoch 27/50
7362/7362 ━━━━━━━━━━━━━━━━━━━━ 23s 3ms/step - loss: 23.9027 - val_loss: 24.0373
Epoch 28/50
7362/7362 ━━━━━━━━━━━━━━━━━━━━ 21s 3ms/step - loss: 23.9026 - val_loss: 24.0393
Epoch 29/50
7362/7362 ━━━━━━━━━━━━━━━━━━━━ 21s 3ms/step - loss: 23.9027 - val_loss: 24.0370
Epoch 30/50
7362/7362 ━━━━━━━━━━━━━━━━━━━━ 23s 3ms/step - loss: 23.9025 - val_loss: 24.0372
Epoch 31/50
7362/7362 ━━━━━━━━━━━━━━━━━━━━ 23s 3ms/step - loss: 23.9025 - val_loss: 24.0371
Epoch 32/50
7362/7362 ━━━━━━━━━━━━━━━━━━━━ 43s 3ms/step - loss: 23.9025 - val_loss: 24.0368
Epoch 33/50
7362/7362 ━━━━━━━━━━━━━━━━━━━━ 38s 3ms/step - loss: 23.9023 - val_loss: 24.0370
Epoch 34/50
7362/7362 ━━━━━━━━━━━━━━━━━━━━ 21s 3ms/step - loss: 23.9024 - val_loss: 24.0368
Epoch 35/50
7362/7362 ━━━━━━━━━━━━━━━━━━━━ 22s 3ms/step - loss: 23.9022 - val_loss: 24.0367
Epoch 36/50
7362/7362 ━━━━━━━━━━━━━━━━━━━━ 41s 3ms/step - loss: 23.9022 - val_loss: 24.0367
Epoch 37/50
7362/7362 ━━━━━━━━━━━━━━━━━━━━ 40s 3ms/step - loss: 23.9021 - val_loss: 24.0368
Epoch 38/50
7362/7362 ━━━━━━━━━━━━━━━━━━━━ 43s 3ms/step - loss: 23.9020 - val_loss: 24.0369
Epoch 39/50
7362/7362 ━━━━━━━━━━━━━━━━━━━━ 22s 3ms/step - loss: 23.9020 - val_loss: 24.0367
Epoch 40/50
7362/7362 ━━━━━━━━━━━━━━━━━━━━ 20s 3ms/step - loss: 23.9020 - val_loss: 24.0367
Epoch 41/50
7362/7362 ━━━━━━━━━━━━━━━━━━━━ 19s 3ms/step - loss: 23.9021 - val_loss: 24.0363
Epoch 42/50
7362/7362 ━━━━━━━━━━━━━━━━━━━━ 22s 3ms/step - loss: 23.9019 - val_loss: 24.0363
Epoch 43/50
7362/7362 ━━━━━━━━━━━━━━━━━━━━ 40s 3ms/step - loss: 23.9018 - val_loss: 24.0365
Epoch 44/50
7362/7362 ━━━━━━━━━━━━━━━━━━━━ 20s 3ms/step - loss: 23.9018 - val_loss: 24.0383
Epoch 45/50
7362/7362 ━━━━━━━━━━━━━━━━━━━━ 21s 3ms/step - loss: 23.9018 - val_loss: 24.0363
Epoch 46/50
7362/7362 ━━━━━━━━━━━━━━━━━━━━ 23s 3ms/step - loss: 23.9019 - val_loss: 24.0361
Epoch 47/50
7362/7362 ━━━━━━━━━━━━━━━━━━━━ 25s 3ms/step - loss: 23.9019 - val_loss: 24.0362
Epoch 48/50
7362/7362 ━━━━━━━━━━━━━━━━━━━━ 23s 3ms/step - loss: 23.9015 - val_loss: 24.0364
Epoch 49/50
7362/7362 ━━━━━━━━━━━━━━━━━━━━ 21s 3ms/step - loss: 23.9018 - val_loss: 24.0360
Epoch 50/50
7362/7362 ━━━━━━━━━━━━━━━━━━━━ 23s 3ms/step - loss: 23.9018 - val_loss: 24.0361

In [81]:
y_pred_ann = model.predict(X_test_scaled)
y_pred_ann = y_pred_ann.flatten()

2301/2301 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step

In [82]:
mae_ann = mean_absolute_error(y_test_k, y_pred_ann)
mse_ann = mean_squared_error(y_test_k, y_pred_ann)
rmse_ann = mse_ann ** 0.5
r2_ann = r2_score(y_test_k, y_pred_ann)

In [83]:
print("ANN Results")
print("MAE :", mae_ann)
print("MSE :", mse_ann)
print("RMSE:", rmse_ann)
print("R²  :", r2_ann)

ANN Results
MAE : 3.944477027723002
MSE : 23.951185285584373
RMSE: 4.893994818712457
R²  : -0.0002897214154600203

In [84]:
comparison = pd.DataFrame({
    "Model": [
        "Linear Regression",
        "Decision Tree",
        "KNN",
        "ANN"
    ],
    "MAE": [
        mae_kbest,
        mae_dt,
        mae_knn,
        mae_ann
    ],
    "RMSE": [
        rmse_kbest,
        rmse_dt,
        rmse_knn,
        rmse_ann
    ],
    "R2": [
        r2_kbest,
        r2_dt,
        r2_knn,
        r2_ann
    ]
})

comparison

               Model       MAE      RMSE        R2
0  Linear Regression  3.944615  4.893454 -0.000069
1      Decision Tree  3.944861  4.893711 -0.000174
2                KNN  4.166899  5.176322 -0.119029
3                ANN  3.944477  4.893995 -0.000290

In [85]:
#Four predictive models were evaluated using selected features.
#Linear Regression achieved the best overall performance,
#although all models produced low predictive accuracy due to the weak relationships between the available features and response time.